# config/application.yml
defaults: &defaults
  mp3_folder: <%= "#{Rails.root}/public/music/songs" %>
  mp3_url: "/music/songs"
  mp3_unsorted_folder : <%= "#{Rails.root}/public/music/unsorted_songs" %>
  apikey: "352e35485dead90ec0179be83979e561"
  secret: "d3044af5b2569b22b024a177d0cc555d"
  acoustid: "8hxIerS0"

  USER_NAME: "user"
  USER_PASSWORD: "useruser123"
  USER_EMAIL: "user@user.de"
  ADMIN_NAME: "admin"
  ADMIN_EMAIL: "admin@admin.de"
  ADMIN_PASSWORD: "adminadmin123"
  ROLES: [admin, user, waiting]

  REQUIRE_UNLOCK: false
  DEFAULT_ADMIN: true
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults