# config/application.yml
defaults: &defaults
  mp3_folder: <%= "#{Rails.root}/public/music/songs" %>
  mp3_unsorted_folder : <%= "#{Rails.root}/public/music/unsorted_songs" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults